language: node_js
node_js:
  - '8'

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"  master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/fuzhouxxdong/myblog.git
