language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "fuzhouxxdong"
  - git config user.email "fuzhouxxdong@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push origin gh-pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"  gh-pages:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/fuzhouxxdong/fuzhouxxdong.github.io.git
